version: "3"

services:

  nginx:
    image: nginx:latest
    container_name: corso-php-ciraolo-nginx
    hostname: corso-php-ciraolo
    volumes:
      - ./../:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    links:
      - phpfpm

  phpfpm:
    build:
      context: ./..
      dockerfile: docker/PHP.Dockerfile
    container_name: corso-php-ciraolo-phpfpm
    volumes:
      - ./../:/var/www/html
      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
